#version 450 core
layout(local_size_x = 8, local_size_y = 8) in;

uniform isampler2D ref_id;
uniform int maxID;
uniform float globalSplatSize;

struct Point {
    int  pointID;
    vec3 position; float _padA;
    vec3 color;    float _padB;
    vec3 normal;   float _padC;
    float splatSize;
};

struct NormalBuffer {
    vec3 normal;
    int counter;
};

struct DensityBuffer {
    float densitySum;
    int counter;
};

layout(std430, binding = 0) buffer NormalSumBuffer { NormalBuffer normalBuffer[]; }; // calculated normals
layout(std430, binding = 2) buffer PointBuffer     { Point points[]; }; // store them here to later pass them to CPU side
layout(std430, binding = 4) buffer DensitySumBuffer { DensityBuffer densityBuffer[]; }; // for density of splats

void main() {
    ivec2 currentPos = ivec2(gl_GlobalInvocationID.xy);
    int currentID = texelFetch(ref_id, currentPos, 0).r;

    // skip calculation for pixels with no valid id (most likely empty) and empty IDs, if no normals was gathered
    if (currentID < 0 || currentID > maxID) return;
    if (normalBuffer[currentID].counter <= 0) return;

    // if the normal is (0,0,0) or NaN dont include it in the calculation
    if (any(isnan(normalBuffer[currentID].normal)) || length(normalBuffer[currentID].normal) < 1e-6) {
        return;
    }

    // assign the normal to the point cloud, normalize to make it even length
    // use reference texture to only assign to pixels with a point
    points[currentID].normal = normalize(normalBuffer[currentID].normal);
    
    // adaptive splat size
    points[currentID].splatSize = 2;
}
