#version 450 core
layout(local_size_x = 256) in;

uniform int maxID;

struct Point {
    int  pointID;
    vec3 position; float _padA;
    vec3 color;    float _padB;
    vec3 normal;   float _padC;
    float splatSize;
};

struct NormalStats {
    uint occludedNrml;
    uint goodNrml;
    uint mediumNrml;
    uint badNrml;
};

uniform float goodNormal;
uniform float badNormal;

vec3 invisible = vec3(0.141f, 0.149f, 0.192f);


layout(std430, binding = 1) buffer PointGTBuffer { Point pointsGT[]; }; // ground truth points
layout(std430, binding = 2) buffer PointBuffer     { Point points[];   }; // calculated points
layout(std430, binding = 3) buffer StatsBuffer   { NormalStats stats; };

void main() {
    uint currentID = gl_GlobalInvocationID.x;

     if (currentID < 0 && currentID > maxID) 
        return;

    vec3 normal   = points[currentID].normal;
    vec3 normalGT = pointsGT[currentID].normal;

    if (any(isnan(normal)) || normal == vec3(0)) {
      atomicAdd(stats.occludedNrml, 1u);
      points[currentID].color = invisible;
      return;
    }

    normal   = normalize(normal);
    normalGT = normalize(normalGT);
    if (dot(normal, normalGT) < 0.0) normal = -normal;

    float d = clamp(dot(normal, normalGT), -1.0, 1.0);
    float theta = degrees(acos(d));

    if (theta <= goodNormal) {
        atomicAdd(stats.goodNrml, 1u);
    } else if (theta <= badNormal) {
        atomicAdd(stats.mediumNrml, 1u);
    } else {
        atomicAdd(stats.badNrml, 1u);
        points[currentID].color = vec3(1.0, 0.0, 0.0);
    }
}
