#version 450 core 
#extension GL_NV_shader_atomic_float : enable
layout(local_size_x = 8, local_size_y = 8) in;

uniform sampler2D  splat_depth;
uniform isampler2D splat_id;

uniform sampler2D  ref_depth;
uniform isampler2D ref_id;

uniform ivec2 screenSize;
uniform mat4 invProj;
uniform mat4 view;
uniform mat4 proj;
uniform mat4 invView;
uniform float maxID;

uniform float zFar;
uniform float zNear;

uniform float distanceWeight = 3; 
uniform float depthThreshold;
uniform float depthCutoff = 0.01;

struct NormalBuffer{
    vec3 normal;
    int counter;
};

struct DensityBuffer {
    float densitySum;
    int counter;
};

// construct 5x5 kernel
const ivec2 offsets[9] = ivec2[9](
    ivec2(-1,  1), ivec2(0,  1), ivec2(1,  1),
    ivec2(-1,  0), ivec2(0,  0), ivec2(1,  0),
    ivec2(-1, -1), ivec2(0, -1), ivec2(1, -1)
);

vec3 kernelPositions[9];
float kernelWeights[9];

layout(std430, binding = 0) buffer NormalSumBuffer { NormalBuffer normalBuffer[]; };
layout(std430, binding = 4) buffer DensitySumBuffer { DensityBuffer densityBuffer[]; };

vec3 getPos(ivec2 fragCoord, float depth) {
    vec2 ndc = ((vec2(fragCoord) + 0.5) / vec2(screenSize)) * 2.0 - 1.0;
    float ndcDepth = depth * 2.0 - 1.0;
    vec4 clipSpace = vec4(ndc, ndcDepth, 1.0);
    vec4 viewSpace = invProj * clipSpace;
    viewSpace /= viewSpace.w;
    return viewSpace.xyz;
}

void main() {
	// get depth and ID from splat texture
    ivec2 currentPixelPos = ivec2(gl_GlobalInvocationID.xy);
    float currentPixelDepth = texelFetch(splat_depth, currentPixelPos, 0).r;
    int currentPixelID = texelFetch(splat_id, currentPixelPos,0).r;

    // no calculation for empty pixels
    if(currentPixelID > maxID || currentPixelID < 0)
        return;

    // discard pixels outside of the screen
    if (currentPixelPos.x <= 0 || currentPixelPos.y <= 0 || currentPixelPos.x >= screenSize.x - 1 || currentPixelPos.y >= screenSize.y - 1) 
        return;
    
    // reconstruct current point
    vec3 reconstructedPoint = getPos(currentPixelPos, currentPixelDepth);

    vec3 normalSum = vec3(0);
    float sumDist = 0.0;
    int   distCount = 0;

    // 5x5 KERNEL calculation
    for (int i = 0; i < 9; ++i)
    {
        // get current neighbor point of loop
        ivec2 kernelCoord = currentPixelPos + offsets[i];
        float kernelDepth = texelFetch(splat_depth, kernelCoord,0).r;
        int neighborID = texelFetch(splat_id, kernelCoord, 0).r;
        vec3 neighborPoint = getPos(kernelCoord, kernelDepth);

        float depthDifference = neighborPoint.z - reconstructedPoint.z;
       
       // define weights for gaussian kernels in bilateral weighting (spatial and depth weight)

        float spatialWeight = exp(-dot(offsets[i],offsets[i]) / (2.0 * distanceWeight * distanceWeight)); // pixel distance influences weight
        float depthWeight = exp(-(depthDifference*depthDifference) / (2.0 * depthThreshold * depthThreshold)); // depth difference influences weight
        float combinedWeight = spatialWeight * depthWeight;

        // distance calculation for densitiy within kernel
        // use reference texture for distance 
        ivec2 kernelCoordRef = currentPixelPos + offsets[i];
        int neighborIDRef = texelFetch(ref_id, kernelCoordRef, 0).r;
        float kernelDepthRef = texelFetch(ref_depth, kernelCoord,0).r;
        vec3 neighborPointRef = getPos(kernelCoord, kernelDepth);

        if (neighborIDRef < 0 || neighborIDRef > maxID) {
            continue; 
    }

        // calc distance for splat size
        if (combinedWeight < 1e-6) {
            kernelPositions[i] = vec3(0); //invalid neighbor
            kernelWeights[i]   = 0.0;
        } else {
            kernelPositions[i] = neighborPoint;
            kernelWeights[i]   = combinedWeight;

            float dist = length(neighborPointRef - reconstructedPoint);
            if (dist > 1e-6) {
                sumDist += dist;
                distCount++;
            }
        }
    }

    // Kernel neighbor calculation

    vec3 leftNext  = kernelPositions[3];   // -1,  0
    vec3 rightNext = kernelPositions[5];   // +1,  0
    
    vec3 upNext    = kernelPositions[1];   //  0, -1
    vec3 downNext  = kernelPositions[7];   //  0, +1
    
    vec3 upLeft    = kernelPositions[0];   // -1, -1
    vec3 upRight   = kernelPositions[2];   // +1, -1
    vec3 downLeft  = kernelPositions[6];   // -1, +1
    vec3 downRight = kernelPositions[8];   // +1, +1
        

    if (length(rightNext) > 1e-6 && length(leftNext) > 1e-6 &&
        length(upNext)    > 1e-6 && length(downNext) > 1e-6) {

        float wpair = kernelWeights[5] * kernelWeights[3] *
                      kernelWeights[1] * kernelWeights[7];
        if (wpair > 1e-6) {
            normalSum += wpair * normalize(cross(rightNext - leftNext, upNext - downNext));
        }
    }

    if (length(downLeft)  > 1e-6 && length(upRight)   > 1e-6 &&
        length(downRight) > 1e-6 && length(upLeft)    > 1e-6) {

        float wpair = kernelWeights[6] * kernelWeights[2] *
                      kernelWeights[8] * kernelWeights[0];
        if (wpair > 1e-6) {
            normalSum += wpair * normalize(cross(downLeft - upRight, downRight - upLeft));
        }
    }
    
    // transform to world space
    vec3 normal = normalize(mat3(invView) * normalSum); 

    // count normals

    atomicAdd(normalBuffer[currentPixelID].normal.x, normal.x);
    atomicAdd(normalBuffer[currentPixelID].normal.y, normal.y);
    atomicAdd(normalBuffer[currentPixelID].normal.z, normal.z);
    atomicAdd(normalBuffer[currentPixelID].counter, 1);

    // sum up distance

    if (distCount > 0) {
        float meanDist = sumDist / float(distCount);
        float density = 1.0 / meanDist; 
        atomicAdd(densityBuffer[currentPixelID].densitySum, density);
        atomicAdd(densityBuffer[currentPixelID].counter, 1);
    }
}